### ISSUE TITLE
Get the 3 seperate instances set up and running

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#106]
### To-Do
Set up the 3 separate instances of the platform using the variables desired by the seperate events.

### Variables are attached
https://docs.google.com/document/d/1dlh3g8epKxZsgcRANs6EWf2f5E26zSfV26a2E3tVoCE/edit

### Technical issues/requirements

**Comment by Wardormeur** [comment]
If we're going for generic custom questions, https://github.com/CoderDojo/coolest-platform/issues/88 is blocking

**Comment by Wardormeur** [comment]
That also means : 
 - deploying a new namespace for uk (each namespace is behind a LB, so we can't stack every pods in one)
 - modifying usa's namespace's deployment to use the pods from master instead of the :usa branch

**Comment by Wardormeur** [comment]
Change of plan : 
  - each namespace will have its image.
The reason behind is that the env_var is required at the image build time (because that's when the frontend is built). Making an image that rebuild it's own frontend on start (where the k8s env var are available) is against the notion of immutability of images.
That means that the kube.sh script needs to hardcode every branches so that we can apply the env_var (GA key, event_slug ...)

**Comment by Wardormeur** [comment]
The fact that we have 3 instances running, but you want the same domain (register.coolestprojects) is fairly annoying.
Each stack has its own "base url" that is /event/[cp-2018|usa-2018...]. DNS cannot resolve a path, so that mean a front proxy to every pods (which are in different namespaces..., so like, not easy) and assume that everybody >will< use the proper end path. There is no way to use "register.coolestprojects" and magically redirect to the right instance (being int, usa or uk).
I would hardly recommend using the same hack than last year, registerna/registeruk/registerxxx

**Comment by conoramurphy** [comment]
Ah sorry. Then changing the base URL per event is fine if that is significantly easier. So I'll chase up a slightly different URL scheme. 

What URL scheme do you want if you could choose, as say you don't want this one OR last years one in your ticket.

**Comment by Wardormeur** [comment]
> I would hardly recommend using the same hack than last year
So anything that doesn't have the same subdomain is fine :)

**Comment by conoramurphy** [comment]
So last years scheme? Since last year had a different subdomain per event.
e.g. something like this would do?

register-international.cooles...
register-usa.cooles...
register-uk.cooles...

**Comment by Wardormeur** [comment]
TBD:

- [ ] set the db password into k8s
- [ ] set the logentries keys /namespace
- [ ] set the minimum instance to 1
- [ ] create the event per instance

**Comment by Wardormeur** [comment]
Do we stick with the yearly based domain @conoramurphy  ?

**Comment by conoramurphy** [comment]
Yep, yearly domains.

**Comment by Wardormeur** [comment]
Missing data : 
 - event date
 - registration opening date

**Comment by Wardormeur** [comment]
Uncompleted data:
 - Int: 
   - ticketing_uri

**Comment by Wardormeur** [comment]
@conoramurphy added missing data

**Comment by conoramurphy** [comment]
@Wardormeur 

Sorry about delay.
 - We won't have the ticketing URL for the platforms till next week. (And maybe later than that)
 - Event date DOH! Added to the doc
 - Registration opening date added to the doc, 

Note for the dates, are any of them strings vs date variables. Just checking do i need to format them

**Comment by Wardormeur** [comment]
No need to format, it's k

**Comment by Wardormeur** [comment]
Updated

**Comment by Wardormeur** [comment]
The changes are live since ^, but I'm keeping the ticket around until we have the ticketing_url

**Comment by conoramurphy** [comment]
Just checking, should the register-international-2019.coolestprojects.org be now able to accept projects then? (We're past the registration open date)

Or did I misunderstand something

**Comment by Wardormeur** [comment]
@conoramurphy Regarding next monday : is this the launch of every instances of CP?
If so, I'm still missing some external_ticketing_uri for USA

**Comment by conoramurphy** [comment]
I sent them all an email saying you will reset confirm email counter and that's probably it tomorrow. They can nuke other tests themselves.

**Comment by conoramurphy** [comment]
https://www.eventbrite.com/e/coolest-projects-usa-tickets-53707779414 sorry

**Comment by Wardormeur** [comment]
Closing, all good configuration-side
