### ISSUE TITLE
Create new accounts for everybody

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#126]
## Task
Create new accounts for everybody and send them their password. Note there will probably be 2/3 additions before the events and we'll just have to accommodate that.

I added myself for testing/debugging purposes.

### For USA
- [x] Amy amy@coderdojo.org
- [x] Rosa rosa@coderdojo.org
- [x] Christina christina@raspberrypi.org
- [x] Conor conor@coderdojo.org
- [x] Matt matt@raspberrypi.org

### For INT
- [x] Amy amy@coderdojo.org
- [x] Rosa rosa@coderdojo.org
- [x] Sinead sinead@coderdojo.org
- [x] Conor conor@coderdojo.org
- [x] Rachel rachel.lavin@raspberrypi.org

### For UK
- [x] Amy amy@coderdojo.org
- [x] Rosa rosa@coderdojo.org
- [x] Helen drury helen.drury@raspberrypi.org
- [x] Tom tom.evans@raspberrypi.org
- [x] Conor conor@coderdojo.org

**Comment by conoramurphy** [comment]
Please don't do this until we've properly reviewed the text and got all that fun done. Otherwise we'll have people reviewing this at a partial finish point.

**Comment by Wardormeur** [comment]
Better use a generic account for webteam than just for you @conoramurphy

**Comment by Wardormeur** [comment]
Ticked you conor as you will be using the account on https://github.com/CoderDojo/coolest-platform/issues/143

**Comment by Wardormeur** [comment]
Done
