### ISSUE TITLE
Updates to image generation for CP Int 2019

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#199]
**Business Goal**
Get the desk sheets, lanyards and judging sheets sent to the printers by Monday if possible (note if overruns no biggie)

Sheet: https://docs.google.com/spreadsheets/d/1Jj-dGkddXxwEOVJwiMZl9H4hDzxcWGZer6RAAieabrI/edit#gid=0

**Tasks**
- [x] Wait for close and cleanup, generate seating off that #199 
- [ ] Wait until all the extra info around judging and stage times is added to the sheet and shared with us.
- [ ] We need to update the script/sheet generating the CP Int images and add innovator stage times as well in the space below Guardian contact number with the label "Innovator Stage Time". If there is no Innovator Stage Time for that project just leave field and label blank.
- [ ] Then run it and upload the generated images and share into the #coolestprojectsdublin slack channel notifying me, sinead and rosa.

We are generating desksheet and lanyards and judging sheets. Attached are the blanks.

**Blank pdfs**

[CPINT_Lanyard_Badge_FINAL_PRINT.pdf](https://github.com/CoderDojo/coolest-platform/files/3116564/CPINT_Lanyard_Badge_FINAL_PRINT.pdf)
[CPINT_Project_Desk_Sheet_FINAL_PRINT.pdf](https://github.com/CoderDojo/coolest-platform/files/3116567/CPINT_Project_Desk_Sheet_FINAL_PRINT.pdf)
[CPINT_A4_Judges_Sheet_FINAL_PRINT.pdf](https://github.com/CoderDojo/coolest-platform/files/3117758/CPINT_A4_Judges_Sheet_FINAL_PRINT.pdf)

Wifi: coolestprojects
Password: onerulebecool
