### ISSUE TITLE
Updates to desk number script for CP Int 2019

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#200]
### Business Goal
Be able to quickly generate desk numbers in the coolest projects platform based on some categories having age groups to split down the group size and some categories do not.

### Groups 
Number of projects indicative only, nothing about group sizes should be hardcoded. Ages are most important here.

**Advanced** - 27 projects
**Design** - 17 projects
**Mobile** - 32 projects
**Games** - 99 projects
_11 & under_ - 58
_12 +_ - 41
**Hardware** 105
_12 & under_ 50 projects
_13+_ 55 projects
**Visual programming** 241 projects
_8 & under_ 53 projects
_9 - 44_ projects
_10 - 53_ projects
_11 - 34_ projects
_12 & over_ 57
**Web** - 62 projects
_12 & under_  37 projects
_12 +_ - 35 projects

### Task detail
**Ordering formula**
Each category is treated independently so the desk numbers reset between categories but not age groups. 

Split into ages as listed above, so increment the desk number per project, then by org_reference code.

This will have the effect of putting club members who are in the same category and age group to be beside each other.

**Category shortcodes**
Advanced: ADV, 
Design: DES,  
Mobile: MOB, 
Games: GAM, 
Visual programming: VIS,
Hardware: HW,
Web: WEB

**Desk number Format with examples**
[Category shortcode][Age Group number]-[Order in category]
Examples according to the group size
for the first project in WEB under 12: WEB1-101 (100+ 1st in category)
for the 3rd project in WEB over 12: WEB2-140 (100 + 40th in category (37 in group 1 + 3))
for the 2nd project in VIS programming under 8: VIS1:102 (100+2nd in category)

**To review**
Afterwards we should check some examples that meet the criteria
- [ ] Check that the highest desk numbers add up to the right number of projects - 600 (for the 100 increments)
- [ ] Check several projects are in the right category and age group
- [ ] Check ones that meet the above AND are in the same org

**Comment by Wardormeur** [comment]
Awaiting info regarding number of exceptions seats and their continuity

**Comment by Wardormeur** [comment]
The creation of so many fragmentation of age group per category means users are very unlikely to be grouped per club. This was only the case last year if you had kids between 10<12, but now will happen for each categories.
Small typo in the examples, VIS1-102 is 2nd in category, not 1st
