### ISSUE TITLE
Coolest Platform 2020 launch

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#211]
#### Start platform
- [x] Get custom variables per event (https://docs.google.com/document/d/1rvzyeaDRcd6fYTuvCwH7KBp5BprhSEP880ZyDFtm1Uc/edit?usp=sharing)
- [x] Kick up the platform
- [x] Set custom variables (2019 doc)
- [x] Test emails (sendgrid)
- [x] Invite the admins (there's a tool for this)
- [x] Get feedback and cleanup https://github.com/CoderDojo/coolest-platform/issues/225
- [x] It's live!
- [x] Update the coolestprojects.org site with tweaks as the "launch" for USA and UK
- [x] It's launched!
- [x] Document the above in detail so it could be replicated with 0 help
